version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - /app/.next
    command: npm run dev
    ports:
      - "4200:4200"

volumes:
  node_modules:
